### ISSUE TITLE
Cloning the repository to Vercel did not work for me

### ISSUE THREAD

**Issue by ZiadJ** [ajcwebdev/ajcwebdev-nuxt3#1]
I made a clone of the repository and published it on [Vercel](https://ajcwebdev-nuxt3-235rlha94-ziadj.vercel.app/) but can't seem to be able to navigate to the pages from there. I'm new to serverless functions and stuff so I thought I'd raise this issue just in case anyone might help.

**Comment by ajcwebdev** [comment]
Hi @ZiadJ! Thanks for opening this issue. Nuxt3 is still in active development so things are changing every few months. The previous setup wasn't using `NuxtPage` correctly. I made some changes and you should be able to clone the current version and deploy it successfully to Vercel. Here's the deployed version of the current `main` branch:

- https://ajcwebdev-nuxt3.vercel.app/
- https://ajcwebdev-nuxt3.vercel.app/about
- https://ajcwebdev-nuxt3.vercel.app/graphql
- https://ajcwebdev-nuxt3.vercel.app/api

`/api` will show you the output of the serverless function in `index.js`.

<img width="640" alt="Screenshot of Nuxt 3 API route output" src="https://user-images.githubusercontent.com/12433465/184405611-41bff332-6d04-4535-acf4-2abc8ad3ef2f.png">
